name: Codemeta2CFF

runs:
  using: "composite"
  steps:
    - name: wget
      run: wget -O datatools.zip https://github.com/caltechlibrary/datatools/releases/download/v1.0.4-dev/datatools-1.0.4-dev-linux-amd64.zip
    - name: unzip
      run: unzip -qq datatools.zip -d datatools
    - nake: mv
      run: mv datatools/codemeta2cff .
    - name: Convert
      run: codemeta2cff
