name: Render

on:
  push:
    branches: main
      tags:
        - v*
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: false
        default: 'Manual trigger'

jobs:
  Render:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: caltechlibrary/codemeta2cff@main
